config/routes.rb
Rails.application.routes.draw do

  scope module: 'site' do
    root 'mains#show'
    get '/p/:alias', to: 'pages#show'
    resource :enroll, only: [:show, :new, :create]
    resources :articles
  end

  namespace :admin do
    get '/', to: 'mains#show'
    get 'login', to: 'sessions#new'
    delete 'logout' => 'sessions#destroy'
    resources :sessions, only: [:create]
    resources :pages, :articles, :article_categories, :foods, :food_categories, :announcements
    resources :enrolls
    resources :enroll_batches do
      patch :switch, on: :member
    end
    resources :administrators
  end
end

app/views/admin/pages/_form.html.erb
<%= simple_form_for [:admin, @page], html: {class: 'form-horizontal'}, wrapper: :horizontal_form do |f| %>
  <div class="box-body">
    <%= f.input :title, label: '标题', placeholder: '请输入单页标题' %>
    <%= f.input :alias, label: '别名', placeholder: '请输入英文别名' %>
    <%= f.input :content, :as => :kindeditor, :label => '单页内容', :input_html => { :width => 800, :height => 300 } %>
  </div>
  <div class="box-footer">
    <%= f.button :submit, '保存' %>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<section class="content-header">
  <h1>
    单页管理
    <small>编辑职位</small>
  </h1>
  <ol class="breadcrumb">
    <li>
      <%= link_to admin_path do %>
        <i class="fa fa-home"></i> 首页
      <% end %>
    </li>
    <li class="active">单页管理</li>
    <li class="active">编辑单页</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">编辑单页</h3>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/admin/pages/index.html.erb
<section class="content-header">
  <h1>
    单页管理
    <small>单页列表</small>
  </h1>
  <ol class="breadcrumb">
    <li>
      <%= link_to admin_path do %>
        <i class="fa fa-home"></i> 首页
      <% end %>
    </li>
    <li>单页管理</li>
    <li class="active">列表</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">
            <div class="btn-group">
              <%= link_to '新增', new_admin_page_path, class: 'btn btn-default btn-xs' %>
            </div>
          </h3>

          <div class="box-tools">

            <%= search_form_for [:admin, @q] do |f| %>
              <div class="input-group input-group-sm" style="width: 150px;">
                <%= f.search_field :title_cont, class: 'form-control pull-right', placeholder: '单页标题' %>

                <div class="input-group-btn">
                  <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <tr>
              <th>标题</th>
              <th>别名</th>
              <th>操作</th>
            </tr>
            <% @pages.each do |page| %>
            <tr>
              <td><%= page.title %></td>
              <td><%= page.alias %></td>
              <td>
                <%= link_to edit_admin_page_path(page), class: 'btn btn-primary btn-xs' do %>
                  <i class="fa fa-edit"></i> 编辑
                <% end %>
                <%= link_to admin_page_path(page), method: :delete, class: 'btn btn-danger btn-xs' do %>
                  <i class="fa fa-trash-o"></i> 删除
                <% end %>
              </td>
            </tr>
            <% end %>
          </table>
        </div>
        <%= paginate @pages, views_prefix: 'admin' %>
      </div>
    </div>
  </div>
</section>

app/views/admin/pages/new.html.erb
<section class="content-header">
  <h1>
    单页管理
    <small>新增单页</small>
  </h1>
  <ol class="breadcrumb">
    <li>
      <%= link_to admin_path do %>
        <i class="fa fa-home"></i> 首页
      <% end %>
    </li>
    <li class="active">单页管理</li>
    <li class="active">新增单页</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">新增单页</h3>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>