config/routes.rb
Rails.application.routes.draw do

  scope module: 'site' do
    root 'mains#show'
    get '/p/:alias', to: 'pages#show'
    resource :enroll, only: [:show, :new, :create]
    resources :articles
  end

  namespace :admin do
    get '/', to: 'mains#show'
    get 'login', to: 'sessions#new'
    delete 'logout' => 'sessions#destroy'
    resources :sessions, only: [:create]
    resources :pages, :articles, :article_categories, :foods, :food_categories, :announcements
    resources :enrolls
    resources :enroll_batches do
      patch :switch, on: :member
    end
    resources :administrators
  end
end

app/views/layouts/shared/_admin_footer.html.erb
<div class="pull-right hidden-xs">
</div>
<strong>Copyright &copy; 2018 <a href="http://codeorder.cn">青岛码序科技有限公司</a>.</strong> All rights
reserved.

app/views/layouts/shared/_admin_header.html.erb
<!-- Logo -->
<%= link_to admin_path, class: 'logo' do %>
<!-- mini logo for sidebar mini 50x50 pixels -->
<span class="logo-mini"><b>K</b>M</span>
<!-- logo for regular state and mobile devices -->
<span class="logo-lg"><b>幼儿园</b>后台管理</span>
<% end %>
<!-- Header Navbar: style can be found in header.less -->
<nav class="navbar navbar-static-top">
  <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
    <span class="sr-only">切换</span>
  </a>

  <div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
      <!-- User Account: style can be found in dropdown.less -->
      <li class="dropdown user user-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <span class="hidden-xs"><%= current_administrator.nickname %></span>
        </a>
        <ul class="dropdown-menu">
          <li class="user-body">
            <div class="row">
              <div class="col-xs-4 text-center">
                <a href="#">Followers</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Sales</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Friends</a>
              </div>
            </div>
            <!-- /.row -->
          </li>
          <!-- Menu Footer-->
          <li class="user-footer">
            <div class="pull-left">
              <a href="#" class="btn btn-default btn-flat">Profile</a>
            </div>
            <div class="pull-right">
              <%= link_to '登出', admin_logout_path, method: :delete, class: 'btn btn-default btn-flat' %>
            </div>
          </li>
        </ul>
      </li>
    </ul>
  </nav>

app/views/layouts/shared/_admin_sidebar.html.erb
<section class="sidebar">
  <!-- sidebar menu: : style can be found in sidebar.less -->
  <ul class="sidebar-menu" data-widget="tree">
    <li>
      <%= link_to admin_path do %>
      <i class="fa fa-home"></i>
      <span>首页</span>
      <% end %>
    </li>
    <li class="header">内容管理</li>
    <li>
      <%= link_to admin_articles_path do %>
      <i class="fa fa-newspaper-o"></i>
      <span>资讯管理</span>
      <% end %>
    </li>
    <li>
      <%= link_to admin_pages_path do %>
      <i class="fa fa-file-text-o"></i>
      <span>单页管理</span>
      <% end %>
    </li>
    <li class="header">招生管理</li>
    <li>
      <%= link_to admin_enroll_batches_path do %>
      <i class="fa fa-paper-plane"></i>
      <span>招生简章</span>
      <% end %>
    </li>
    <li>
      <%= link_to admin_enrolls_path do %>
      <i class="fa fa-child"></i>
      <span>报名申请</span>
      <span class="pull-right-container">
        <% enroll_count = Enroll.submit.count %>
        <small class="label pull-right bg-blue"><%= enroll_count %></small>
      </span>
      <% end %>
    </li>
    <li class="header">系统管理</li>
    <li>
      <%= link_to admin_administrators_path do %>
      <i class="fa fa-users"></i>
      <span>管理员管理</span>
      <% end %>
    </li>
    <li class="treeview">
      <a href="#">
        <i class="fa fa-gears"></i> <span>基础信息设置</span>
        <span class="pull-right-container">
          <i class="fa fa-angle-left pull-right"></i>
        </span>
      </a>
      <ul class="treeview-menu">
        <li>
          <%= link_to admin_article_categories_path do %>
          <i class="fa fa-gear"></i>
          <span>资讯分类管理</span>
          <% end %>
        </li>
      </ul>
    </li>
    <li class="header">技术支持</li>
    <li>
      <%= link_to admin_articles_path do %>
      <i class="fa fa-book"></i>
      <span>使用指南</span>
      <% end %>
    </li>
  </ul>
</section>

app/views/layouts/shared/_application_footer.html.erb
<div class="container">
  <div class="pull-right">
    <b>幼儿园建站系统</b> 演示版
  </div>
  <div class="pull-left hidden-xs">
  系统由<%= link_to '青岛码序科技有限公司', 'http://codeorder.cn', target: '_blank' %>开发和提供技术支持。
  <div>幼儿园地址：山东省青岛市文登路*号 </div>
  <div>咨询电话：0532-8287***7 <%= link_to '在线报名', new_enroll_path %></div>
  </div>
</div>

app/views/layouts/shared/_application_header.html.erb
<nav class="navbar navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a href="/" class="navbar-brand"><b>幼儿园</b>演示版</a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <i class="fa fa-bars"></i>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to '首页', root_path %>
        </li>
        <li>
          <%= link_to '/p/admission-guide' do %>
            招生简章 <span class="sr-only">(current)</span>
          <% end %>
        </li>
        <li>
          <%= link_to '在线报名', new_enroll_path %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">资讯 <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <!-- <li class="divider"></li> -->
            <% article_categories = ArticleCategory.sorted %>
            <% article_categories.each do |c| %>
              <li>
                <%= link_to c.name, articles_path('q[article_category_id_eq]': c) %>
              </li>
            <% end %>
          </ul>
        </li>
        <li>
          <%= link_to '后台演示地址', admin_path, target: '_blank' %>
        </li>
      </ul>
      <% @q ||= Article.sorted.ransack(params[:q]) %>
      <%= search_form_for @q, class: 'navbar-form navbar-left', role: 'search' do |f| %>
      <div class="form-group">
        <%= f.search_field :title_cont, class: 'form-control', id: 'navbar-search-input', placeholder: '搜索' %>
      </div>
      <% end %>
    </div>
  </div>
  <!-- /.container-fluid -->
</nav>