config/routes.rb
Rails.application.routes.draw do

  scope module: 'site' do
    root 'mains#show'
    get '/p/:alias', to: 'pages#show'
    resource :enroll, only: [:show, :new, :create]
    resources :articles
  end

  namespace :admin do
    get '/', to: 'mains#show'
    get 'login', to: 'sessions#new'
    delete 'logout' => 'sessions#destroy'
    resources :sessions, only: [:create]
    resources :pages, :articles, :article_categories, :foods, :food_categories, :announcements
    resources :enrolls
    resources :enroll_batches do
      patch :switch, on: :member
    end
    resources :administrators
  end
end

app/models/article.rb
# ## Schema Information
#
# Table name: `articles`
#
# ### Columns
#
# Name                               | Type               | Attributes
# ---------------------------------- | ------------------ | ---------------------------
# **`id`**                           | `bigint(8)`        | `not null, primary key`
# **`content(正文)`**                  | `text`             |
# **`title(标题)`**                    | `string`           |
# **`created_at`**                   | `datetime`         | `not null`
# **`updated_at`**                   | `datetime`         | `not null`
# **`article_category_id(资讯分类id)`**  | `integer`          |
#

class Article < ApplicationRecord

  validates :title, presence: true

  scope :sorted, -> { order(created_at: :desc) }

  belongs_to :article_category
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @q = Article.sorted.ransack(params[:q])
    @articles = @q.result.page(params[:page])
  end

  def new
    @article = Article.new
  end

  def create
    article = Article.create(article_params)
    flash[:notice] = '创建成功'
    redirect_to admin_articles_path
  end

  def edit
  end

  def update
    @article.update(article_params)
    flash[:notice] = '修改成功'
    redirect_to admin_articles_path
  end

  def destroy
    @article.destroy
    redirect_to admin_articles_path
  end

  private
  def article_params
    params.require(:article).permit!
  end

  def set_article
    @article = Article.find params[:id]
  end
end

app/controllers/site/articles_controller.rb
class Site::ArticlesController < Site::BaseController
  before_action :set_article, only: :show

  def index
    @q = Article.sorted.ransack(params[:q])
    @articles = @q.result.page(params[:page])
  end

  def show
  end

  private
  def set_article
    @article = Article.find params[:id]
  end
end

app/helpers/site/articles_helper.rb
module Site::ArticlesHelper
end

app/views/admin/articles/_form.html.erb
<%= simple_form_for [:admin, @article], html: {class: 'form-horizontal'}, wrapper: :horizontal_form do |f| %>
  <div class="box-body">
    <%= f.input :title, label: '标题', placeholder: '请输入资讯标题' %>
    <%= f.input :author, label: '作者', placeholder: '资讯作者（选填）' %>
    <%= f.input :article_category_id, collection: ArticleCategory.all, label: '资讯分类', placeholder: '请选择分类', selected: @article.article_category_id %>
    <%= f.input :content, :owner=> @article, :as => :kindeditor, :label => '资讯内容' %>
  </div>
  <div class="box-footer">
    <%= f.button :submit, '保存' %>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<section class="content-header">
  <h1>
    资讯管理
    <small>编辑资讯</small>
  </h1>
  <ol class="breadcrumb">
    <li>
      <%= link_to admin_path do %>
        <i class="fa fa-home"></i> 首页
      <% end %>
    </li>
    <li class="active">资讯管理</li>
    <li class="active">编辑资讯</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">编辑资讯</h3>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/admin/articles/index.html.erb
<section class="content-header">
  <h1>
    资讯管理
    <small>资讯列表</small>
  </h1>
  <ol class="breadcrumb">
    <li>
      <%= link_to admin_path do %>
        <i class="fa fa-home"></i> 首页
      <% end %>
    </li>
    <li>资讯管理</li>
    <li class="active">列表</li>
  </ol>
</section>

<section class="content">
  <% if flash[:notice] %>
  <div class="alert alert-info alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <%= flash[:notice] %>
  </div>
<% end %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">
            <div class="btn-group">
              <%= link_to '新增', new_admin_article_path, class: 'btn btn-default btn-xs' %>
            </div>
          </h3>

          <div class="box-tools">

            <%= search_form_for [:admin, @q] do |f| %>
              <div class="input-group input-group-sm" style="width: 150px;">
                <%= f.search_field :title_cont, class: 'form-control pull-right', placeholder: '资讯标题' %>

                <div class="input-group-btn">
                  <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <tr>
              <th>标题</th>
              <th>作者</th>
              <th>资讯分类</th>
              <th>操作</th>
            </tr>
            <% @articles.each do |article| %>
            <tr>
              <td><%= article.title %></td>
              <td><%= article.author %></td>
              <td><%= article.try(:article_category).try(:name) %></td>
              <td>
                <%= link_to edit_admin_article_path(article), class: 'btn btn-primary btn-xs' do %>
                  <i class="fa fa-edit"></i> 编辑
                <% end %>
                <%= link_to admin_article_path(article), method: :delete, class: 'btn btn-danger btn-xs' do %>
                  <i class="fa fa-trash-o"></i> 删除
                <% end %>
              </td>
            </tr>
            <% end %>
          </table>
        </div>
        <%= paginate @articles, views_prefix: 'admin' %>
      </div>
    </div>
  </div>
</section>

app/views/admin/articles/new.html.erb
<section class="content-header">
  <h1>
    资讯管理
    <small>新增资讯</small>
  </h1>
  <ol class="breadcrumb">
    <li>
      <%= link_to admin_path do %>
        <i class="fa fa-home"></i> 首页
      <% end %>
    </li>
    <li class="active">资讯管理</li>
    <li class="active">新增资讯</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">新增资讯</h3>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>