config/routes.rb
Rails.application.routes.draw do

  scope module: 'site' do
    root 'mains#show'
    get '/p/:alias', to: 'pages#show'
    resource :enroll, only: [:show, :new, :create]
    resources :articles
  end

  namespace :admin do
    get '/', to: 'mains#show'
    get 'login', to: 'sessions#new'
    delete 'logout' => 'sessions#destroy'
    resources :sessions, only: [:create]
    resources :pages, :articles, :article_categories, :foods, :food_categories, :announcements
    resources :enrolls
    resources :enroll_batches do
      patch :switch, on: :member
    end
    resources :administrators
  end
end

app/models/article_category.rb
# ## Schema Information
#
# Table name: `article_categories`
#
# ### Columns
#
# Name                | Type               | Attributes
# ------------------- | ------------------ | ---------------------------
# **`id`**            | `bigint(8)`        | `not null, primary key`
# **`name(分类名)`**     | `string`           |
# **`created_at`**    | `datetime`         | `not null`
# **`updated_at`**    | `datetime`         | `not null`
#

class ArticleCategory < ApplicationRecord

  validates :name, presence: true

  scope :sorted, -> { order(created_at: :asc) }

  has_many :articles
end

app/controllers/admin/article_categories_controller.rb
class Admin::ArticleCategoriesController < Admin::BaseController
  before_action :set_article_category, only: [:show, :edit, :update, :destroy]

  def index
    @q = ArticleCategory.sorted.ransack(params[:q])
    @article_categories = @q.result.page(params[:page])
  end

  def new
    @article_category = ArticleCategory.new
  end

  def create
    article_category = ArticleCategory.create(article_category_params)
    flash[:notice] = '创建成功'
    redirect_to admin_article_categories_path
  end

  def edit
  end

  def update
    @article_category.update(article_category_params)
    flash[:notice] = '修改成功'
    redirect_to admin_article_categories_path
  end

  def destroy
    @article_category.destroy
    redirect_to admin_article_categories_path
  end

  private
  def article_category_params
    params.require(:article_category).permit!
  end

  def set_article_category
    @article_category = ArticleCategory.find params[:id]
  end
end

app/views/admin/article_categories/_form.html.erb
<%= simple_form_for [:admin, @article_category], html: {class: 'form-horizontal'}, wrapper: :horizontal_form do |f| %>
  <div class="box-body">
    <%= f.input :name, label: '资讯分类名称', placeholder: '请输入分类名称' %>
  </div>
  <div class="box-footer">
    <%= f.button :submit, '保存' %>
  </div>
<% end %>

app/views/admin/article_categories/edit.html.erb
<section class="content-header">
  <h1>
    资讯分类设置
    <small>编辑资讯分类</small>
  </h1>
  <ol class="breadcrumb">
    <li>
      <%= link_to admin_path do %>
        <i class="fa fa-home"></i> 首页
      <% end %>
    </li>
    <li class="active">资讯分类设置</li>
    <li class="active">编辑资讯分类</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">编辑资讯分类</h3>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/admin/article_categories/index.html.erb
<section class="content-header">
  <h1>
    资讯分类设置
    <small>资讯分类列表</small>
  </h1>
  <ol class="breadcrumb">
    <li>
      <%= link_to admin_path do %>
        <i class="fa fa-home"></i> 首页
      <% end %>
    </li>
    <li>资讯分类设置</li>
    <li class="active">列表</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">
            <div class="btn-group">
              <%= link_to '新增', new_admin_article_category_path, class: 'btn btn-default btn-xs' %>
            </div>
          </h3>

          <div class="box-tools">

            <%= search_form_for [:admin, @q] do |f| %>
              <div class="input-group input-group-sm" style="width: 150px;">
                <%= f.search_field :name_cont, class: 'form-control pull-right', placeholder: '资讯分类名称' %>

                <div class="input-group-btn">
                  <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <tr>
              <th>资讯分类名称</th>
              <th>操作</th>
            </tr>
            <% @article_categories.each do |article_category| %>
            <tr>
              <td><%= article_category.name %></td>
              <td>
                <%= link_to edit_admin_article_category_path(article_category), class: 'btn btn-primary btn-xs' do %>
                  <i class="fa fa-edit"></i> 编辑
                <% end %>
                <%= link_to admin_article_category_path(article_category), method: :delete, class: 'btn btn-danger btn-xs' do %>
                  <i class="fa fa-trash-o"></i> 删除
                <% end %>
              </td>
            </tr>
            <% end %>
          </table>
        </div>
        <%= paginate @article_categories, views_prefix: 'admin' %>
      </div>
    </div>
  </div>
</section>

app/views/admin/article_categories/new.html.erb
<section class="content-header">
  <h1>
    资讯分类设置
    <small>新增资讯分类</small>
  </h1>
  <ol class="breadcrumb">
    <li>
      <%= link_to admin_path do %>
        <i class="fa fa-home"></i> 首页
      <% end %>
    </li>
    <li class="active">资讯分类设置</li>
    <li class="active">新增资讯分类</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">新增资讯分类</h3>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>